// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.

export type ModuleId =
  | 'foundations'
  | 'power-cooling'
  | 'network'
  | 'storage'
  | 'compute'
  | 'virt-cloud'

export type LabSlug =
  | 'pue-calculator'
  | 'fat-tree-vis'
  | 'vm-live-migration'

export type LessonMeta = {
  num: number | 'P'
  slug: string
  title: string
  moduleId: ModuleId
  labSlug: LabSlug | null
}

export const LESSONS: readonly LessonMeta[] = [
  { num: 1, slug: 'lezione-01', title: "Introduzione ai Data Center", moduleId: 'foundations', labSlug: null },
  { num: 2, slug: 'lezione-02', title: "Architettura e Gestione dei Datacenter", moduleId: 'foundations', labSlug: null },
  { num: 3, slug: 'lezione-03', title: "Gestione dell'Energia e del Raffreddamento nei Data Center", moduleId: 'power-cooling', labSlug: 'pue-calculator' },
  { num: 4, slug: 'lezione-04', title: "Densità, Calore e Raffreddamento Avanzato nei Data Center Moderni", moduleId: 'power-cooling', labSlug: null },
  { num: 5, slug: 'lezione-05', title: "Cablaggio e Tecnologie di Trasmissione", moduleId: 'network', labSlug: null },
  { num: 6, slug: 'lezione-06', title: "Fabric di un Datacenter", moduleId: 'network', labSlug: 'fat-tree-vis' },
  { num: 7, slug: 'lezione-07', title: "Switching", moduleId: 'network', labSlug: null },
  { num: 8, slug: 'lezione-08', title: "Switch e Fabric continua", moduleId: 'network', labSlug: null },
  { num: 9, slug: 'lezione-09', title: "Fabric Avanzato e Introduzione allo Storage", moduleId: 'network', labSlug: null },
  { num: 10, slug: 'lezione-10', title: "Storage — Tecnologie e Principi Fondamentali", moduleId: 'storage', labSlug: null },
  { num: 11, slug: 'lezione-11', title: "Storage: Architetture e Servizi", moduleId: 'storage', labSlug: null },
  { num: 12, slug: 'lezione-12', title: "Storage Avanzato e Introduzione al Compute", moduleId: 'storage', labSlug: null },
  { num: 13, slug: 'lezione-13', title: "Architettura Compute: CPU, GPU e NPU", moduleId: 'compute', labSlug: null },
  { num: 14, slug: 'lezione-14', title: "Server, BMC e Containerizzazione", moduleId: 'compute', labSlug: null },
  { num: 15, slug: 'lezione-15', title: "Virtualizzazione e Containerizzazione", moduleId: 'virt-cloud', labSlug: null },
  { num: 16, slug: 'lezione-16', title: "Virtualizzazione 2 — Live Migration e Gestione del Datacenter Virtuale", moduleId: 'virt-cloud', labSlug: 'vm-live-migration' },
  { num: 17, slug: 'lezione-17', title: "Cloud Computing", moduleId: 'virt-cloud', labSlug: null },
  { num: 18, slug: 'lezione-18', title: "Control Layer, Orchestrazione e SLA", moduleId: 'virt-cloud', labSlug: null },
]

export const LESSONS_BY_SLUG: Record<string, LessonMeta> = Object.fromEntries(
  LESSONS.map((l) => [l.slug, l]),
)

export function lessonsForModule(id: ModuleId): LessonMeta[] {
  return LESSONS.filter((l) => l.moduleId === id)
}

export function neighbourLessons(slug: string): { prev: LessonMeta | null; next: LessonMeta | null } {
  const idx = LESSONS.findIndex((l) => l.slug === slug)
  if (idx === -1) return { prev: null, next: null }
  return {
    prev: idx > 0 ? LESSONS[idx - 1] : null,
    next: idx < LESSONS.length - 1 ? LESSONS[idx + 1] : null,
  }
}
